const STORY_ARCHIVE = "STORY_ARCHIVE";
const STORIES_FETCH = "STORIES_FETCH";
const STORIES_ADD = "STORIES_ADD";
const STORIES_FETCH_ERROR = "STORIES_FETCH_ERROR";
export { STORY_ARCHIVE, STORIES_ADD, STORIES_FETCH, STORIES_FETCH_ERROR };
